"""Cited project event candidates"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007_events"
down_revision: str | None = "0006_relevance"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_extractions",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("relevance_analysis_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("context_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("extractor_version", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("eligible_segments", sa.Integer(), nullable=False),
        sa.Column("api_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("usage_reported_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("processing_token", sa.Uuid(), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(processing_token IS NULL) = (processing_started_at IS NULL)",
            name=op.f("ck_event_extractions_processing_lease"),
        ),
        sa.CheckConstraint(
            "eligible_segments BETWEEN 0 AND 10000 AND api_calls >= 0 AND input_tokens >= 0 "
            "AND output_tokens >= 0 AND usage_reported_calls BETWEEN 0 AND api_calls "
            "AND latency_ms >= 0",
            name=op.f("ck_event_extractions_extraction_bounds"),
        ),
        sa.CheckConstraint(
            "length(cache_key) = 64 AND length(context_fingerprint) = 64",
            name=op.f("ck_event_extractions_fingerprints"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "created_by"],
            ["project_members.project_id", "project_members.user_id"],
            name=op.f("fk_event_extractions_project_id_created_by_project_members"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "relevance_analysis_id"],
            [
                "relevance_analyses.project_id",
                "relevance_analyses.meeting_id",
                "relevance_analyses.id",
            ],
            name=op.f(
                "fk_event_extractions_project_id_meeting_id_relevance_analysis_id_relevance_analyses"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_event_extractions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_extractions")),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "cache_key",
            name=op.f("uq_event_extractions_project_id_meeting_id_cache_key"),
        ),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "id",
            name=op.f("uq_event_extractions_project_id_meeting_id_id"),
        ),
    )
    op.create_index(
        op.f("ix_event_extractions_project_id"), "event_extractions", ["project_id"], unique=False
    )
    op.create_index(
        "ix_event_extractions_project_meeting_created",
        "event_extractions",
        ["project_id", "meeting_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_event_extractions_relevance",
        "event_extractions",
        ["project_id", "meeting_id", "relevance_analysis_id"],
        unique=False,
    )
    op.create_table(
        "extracted_segments",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("utterance_id", sa.Uuid(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_count BETWEEN 0 AND 4", name=op.f("ck_extracted_segments_event_count_bounds")
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "extraction_id"],
            [
                "event_extractions.project_id",
                "event_extractions.meeting_id",
                "event_extractions.id",
            ],
            name=op.f(
                "fk_extracted_segments_project_id_meeting_id_extraction_id_event_extractions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "utterance_id"],
            ["utterances.project_id", "utterances.meeting_id", "utterances.id"],
            name=op.f("fk_extracted_segments_project_id_meeting_id_utterance_id_utterances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_extracted_segments_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_segments")),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "extraction_id",
            "utterance_id",
            name=op.f("uq_extracted_segments_project_id_meeting_id_extraction_id_utterance_id"),
        ),
    )
    op.create_index(
        op.f("ix_extracted_segments_project_id"), "extracted_segments", ["project_id"], unique=False
    )
    op.create_index(
        "ix_extracted_segments_project_meeting_source",
        "extracted_segments",
        ["project_id", "meeting_id", "utterance_id"],
        unique=False,
    )
    op.create_table(
        "project_event_candidates",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("utterance_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("statement", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="CANDIDATE", nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.String(length=1600), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("owner_mention", sa.String(length=120), nullable=True),
        sa.Column("due_date_text", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('REQUIREMENT_CHANGE', 'DECISION', 'COMMITMENT', 'RISK', "
            "'MILESTONE_CHANGE', 'DEPENDENCY', 'OPEN_QUESTION')",
            name=op.f("ck_project_event_candidates_kind_values"),
        ),
        sa.CheckConstraint(
            "statement IN ('PROPOSAL', 'STATEMENT', 'QUESTION', 'NEGATED')",
            name=op.f("ck_project_event_candidates_statement_values"),
        ),
        sa.CheckConstraint(
            "status = 'CANDIDATE'", name=op.f("ck_project_event_candidates_candidate_only")
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1 AND ordinal BETWEEN 0 AND 3",
            name=op.f("ck_project_event_candidates_event_bounds"),
        ),
        sa.CheckConstraint(
            "due_date_text IS NULL OR length(trim(due_date_text)) BETWEEN 1 AND 120",
            name=op.f("ck_project_event_candidates_date_wording_bounds"),
        ),
        sa.CheckConstraint(
            "length(trim(title)) BETWEEN 1 AND 240 AND "
            "length(trim(description)) BETWEEN 1 AND 1600",
            name=op.f("ck_project_event_candidates_text_bounds"),
        ),
        sa.CheckConstraint(
            "owner_mention IS NULL OR length(trim(owner_mention)) BETWEEN 1 AND 120",
            name=op.f("ck_project_event_candidates_owner_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "extraction_id", "utterance_id"],
            [
                "extracted_segments.project_id",
                "extracted_segments.meeting_id",
                "extracted_segments.extraction_id",
                "extracted_segments.utterance_id",
            ],
            name=op.f(
                "fk_project_event_candidates_project_id_meeting_id_extraction_id_utterance_id_extracted_segments"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_event_candidates_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_event_candidates")),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "extraction_id",
            "utterance_id",
            "ordinal",
            name=op.f(
                "uq_project_event_candidates_project_id_meeting_id_extraction_id_utterance_id_ordinal"
            ),
        ),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "id",
            name=op.f("uq_project_event_candidates_project_id_meeting_id_id"),
        ),
    )
    op.create_index(
        "ix_event_candidates_extraction_kind",
        "project_event_candidates",
        ["project_id", "meeting_id", "extraction_id", "kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_event_candidates_project_id"),
        "project_event_candidates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "event_candidate_evidence",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("utterance_id", sa.Uuid(), nullable=False),
        sa.Column("quote", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(quote)) BETWEEN 1 AND 500",
            name=op.f("ck_event_candidate_evidence_quote_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "candidate_id"],
            [
                "project_event_candidates.project_id",
                "project_event_candidates.meeting_id",
                "project_event_candidates.id",
            ],
            name=op.f(
                "fk_event_candidate_evidence_project_id_meeting_id_candidate_id_project_event_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "utterance_id"],
            ["utterances.project_id", "utterances.meeting_id", "utterances.id"],
            name=op.f("fk_event_candidate_evidence_project_id_meeting_id_utterance_id_utterances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_event_candidate_evidence_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_candidate_evidence")),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "candidate_id",
            "utterance_id",
            name=op.f(
                "uq_event_candidate_evidence_project_id_meeting_id_candidate_id_utterance_id"
            ),
        ),
    )
    op.create_index(
        op.f("ix_event_candidate_evidence_project_id"),
        "event_candidate_evidence",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_event_evidence_project_meeting_source",
        "event_candidate_evidence",
        ["project_id", "meeting_id", "utterance_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_evidence_project_meeting_source", table_name="event_candidate_evidence")
    op.drop_index(
        op.f("ix_event_candidate_evidence_project_id"), table_name="event_candidate_evidence"
    )
    op.drop_table("event_candidate_evidence")
    op.drop_index(
        op.f("ix_project_event_candidates_project_id"), table_name="project_event_candidates"
    )
    op.drop_index("ix_event_candidates_extraction_kind", table_name="project_event_candidates")
    op.drop_table("project_event_candidates")
    op.drop_index("ix_extracted_segments_project_meeting_source", table_name="extracted_segments")
    op.drop_index(op.f("ix_extracted_segments_project_id"), table_name="extracted_segments")
    op.drop_table("extracted_segments")
    op.drop_index("ix_event_extractions_relevance", table_name="event_extractions")
    op.drop_index("ix_event_extractions_project_meeting_created", table_name="event_extractions")
    op.drop_index(op.f("ix_event_extractions_project_id"), table_name="event_extractions")
    op.drop_table("event_extractions")
    # ### end Alembic commands ###
