"""versioned candidate comparison snapshots"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008_deltas"
down_revision: str | None = "0007_events"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_unique_constraint(
        op.f("uq_project_event_candidates_project_id_meeting_id_id_extraction_id"),
        "project_event_candidates",
        ["project_id", "meeting_id", "id", "extraction_id"],
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delta_comparison_runs",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("context_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comparator_version", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("api_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("usage_reported_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("processing_token", sa.Uuid(), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(processing_token IS NULL) = (processing_started_at IS NULL)",
            name=op.f("ck_delta_comparison_runs_processing_lease"),
        ),
        sa.CheckConstraint(
            "api_calls >= 0 AND input_tokens >= 0 AND output_tokens >= 0 AND latency_ms >= 0 "
            "AND usage_reported_calls BETWEEN 0 AND api_calls",
            name=op.f("ck_delta_comparison_runs_usage_bounds"),
        ),
        sa.CheckConstraint(
            "length(cache_key) = 64 AND length(context_fingerprint) = 64",
            name=op.f("ck_delta_comparison_runs_fingerprints"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "created_by"],
            ["project_members.project_id", "project_members.user_id"],
            name=op.f("fk_delta_comparison_runs_project_id_created_by_project_members"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "extraction_id"],
            [
                "event_extractions.project_id",
                "event_extractions.meeting_id",
                "event_extractions.id",
            ],
            name=op.f(
                "fk_delta_comparison_runs_project_id_meeting_id_extraction_id_event_extractions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_delta_comparison_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delta_comparison_runs")),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "cache_key",
            name=op.f("uq_delta_comparison_runs_project_id_meeting_id_cache_key"),
        ),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "id",
            "extraction_id",
            name=op.f("uq_delta_comparison_runs_project_id_meeting_id_id_extraction_id"),
        ),
    )
    op.create_index(
        op.f("ix_delta_comparison_runs_project_id"),
        "delta_comparison_runs",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_delta_runs_project_meeting_created",
        "delta_comparison_runs",
        ["project_id", "meeting_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "project_deltas",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="CANDIDATE", nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("target_version", sa.Integer(), nullable=True),
        sa.Column("target_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=1600), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(outcome NOT IN ('SAME','CHANGE') OR target_id IS NOT NULL) "
            "AND (outcome <> 'NEW' OR target_id IS NULL)",
            name=op.f("ck_project_deltas_target_outcome"),
        ),
        sa.CheckConstraint(
            "outcome IN ('SAME','CHANGE','NEW','UNCLEAR') AND status = 'CANDIDATE'",
            name=op.f("ck_project_deltas_comparison_only"),
        ),
        sa.CheckConstraint(
            "(target_id IS NULL) = (target_version IS NULL) "
            "AND (target_version IS NULL OR target_version >= 1)",
            name=op.f("ck_project_deltas_target_version"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1 AND length(trim(reason)) BETWEEN 1 AND 1600",
            name=op.f("ck_project_deltas_comparison_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "candidate_id", "extraction_id"],
            [
                "project_event_candidates.project_id",
                "project_event_candidates.meeting_id",
                "project_event_candidates.id",
                "project_event_candidates.extraction_id",
            ],
            name=op.f(
                "fk_project_deltas_project_id_meeting_id_candidate_id_extraction_id_project_event_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id", "run_id", "extraction_id"],
            [
                "delta_comparison_runs.project_id",
                "delta_comparison_runs.meeting_id",
                "delta_comparison_runs.id",
                "delta_comparison_runs.extraction_id",
            ],
            name=op.f(
                "fk_project_deltas_project_id_meeting_id_run_id_extraction_id_delta_comparison_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_deltas_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_deltas")),
        sa.UniqueConstraint(
            "project_id",
            "meeting_id",
            "run_id",
            "candidate_id",
            name=op.f("uq_project_deltas_project_id_meeting_id_run_id_candidate_id"),
        ),
    )
    op.create_index(
        op.f("ix_project_deltas_project_id"), "project_deltas", ["project_id"], unique=False
    )
    op.create_index(
        "ix_project_deltas_run_outcome",
        "project_deltas",
        ["project_id", "meeting_id", "run_id", "outcome"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_project_deltas_run_outcome", table_name="project_deltas")
    op.drop_index(op.f("ix_project_deltas_project_id"), table_name="project_deltas")
    op.drop_table("project_deltas")
    op.drop_index("ix_delta_runs_project_meeting_created", table_name="delta_comparison_runs")
    op.drop_index(op.f("ix_delta_comparison_runs_project_id"), table_name="delta_comparison_runs")
    op.drop_table("delta_comparison_runs")
    op.drop_constraint(
        op.f("uq_project_event_candidates_project_id_meeting_id_id_extraction_id"),
        "project_event_candidates",
        type_="unique",
    )
    # ### end Alembic commands ###
